FROM node:16.17.1-buster-slim as build
RUN mkdir -p /home/app
WORKDIR /home/app
COPY . /home/app
RUN npm ci
RUN npm run build

FROM nginx:stable-alpine
COPY --from=build /home/app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 3000
CMD ["nginx", "-g", "daemon off;"]